### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [snurby7/RailsApp#1]
:+1: Looking very nice! Great Bootstrap integration and thanks for introducing me to lorempixel - that's a cool service! And to round it all off, an excellent Skyrim reference. :tada: :balloon: 

As for points of improvement, this certainly isn't something you have to fix, but the more typical (and powerful) way of including Bootstrap in a project is with [the `bootstrap-sass` gem](https://github.com/twbs/bootstrap-sass#a-ruby-on-rails). 

A few cool things about that gem is it allows you to really easily customize which parts of Bootstrap you want to include in your project, you can override Bootstrap's variables to configure how it works before it even compiles into CSS, *and* it requires another gem called `autoprefixer` which automatically adds the appropriate browser prefixes for newer features of CSS, so that you don't have to remember to type stuff like:

``` css
a {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
```

You can just type:

``` css
a {
  box-sizing: border-box;
}
}
